---
title: "PERC Summer Summary"
author: "Nathaniel Grimes"
date: "2022-08-01"
output: pdf_document
---

This summer at PERC helped to greatly condense and solidify my fisheries insurance research. The excellent and supportive feedback from the first seminar led me to shift my research to back out of exploring specific institutional settings, and instead provide clearer justification for how a fishery insurance product would work. Eric, Josh, Sara, and Nic were instrumental in channeling my energy towards more specific outcomes. 

I created a new index insurance model for fisheries to examine fisher demand for insurance and changes to inputs through the "risk reduction" moral hazard. The model demonstrates fishers will change their optimal effort contingent on the risk effects of their inputs. If the fishery is comprised of predominately risk decreasing (increasing) inputs, insurance will lead to less (greater) aggregate effort. Accounting for this re-optimization of inputs more accurately captures conditions fishers will want to buy insurance. There exist insurance contracts that allow insurers to cover administrative costs, but the degree of basis risk, risk aversion, and trigger point are all influential.

My initial goal was to examine fisheries insurance across the insurance spectrum. During the first seminar, there was a great deal of push back on the feasibility of implementing an indemnity based insurance product. The data requirements, institutions that would need to be present, and potential for extreme "Chasing the Trigger" were all valid criticisms of indemnity insurance. Instead there seemed to be greater interest in exploring index insurance because of its flexibility. In addition, index insurance has the most interest from policymakers, so presenting a more concise theory about how it would work and its impact in fisheries could integrate more easily into practical application. I agreed with all these sentiments and adjusted me research plan accordingly. 

One of the first road blocks that I had to tackle was to address the unique nature of different risk effects on fisheries inputs. Without adding this novel theoretical contribution, index insurance would only present an effort increasing effect. However, integrating a new production function into fisheries on top of a unique insurance framework proved to be quite difficult.  After banging my head literally and figuratively, I believe I created a suitable framework to move forward with examining conditions for index insurance to work for both income smoothing and conservation. Though I was not able to achieve as much as I set out to do, I am proud of the conclusions that I found and am excited to keep improving my research.

There are two first order tasks that I still have to complete to polish the paper. First, I need to add fishery dynamics. In my discussion of the impacts insurance has on optimal input use, I conjured up the conservation benefits by simply stating effort reductions lead to more biomass replenishment. Clearly connecting insurance with risk-decreasing inputs to higher stock levels would bolster my argument. Additionally, stock dynamics and status could change the magnitude of insurance of impacts. Second, I want to calibrate the model to weather data to model key insurance viability metrics. My results show insurance can charge beyond actuarially fair premiums, but insurance companies are also concerned about their own risk exposure and not depleting reserves.

The following is a brief list of other ideas that I want to expand, but believe they merit separate papers. 1) What correlations exist between fisheries and weather that would be suitable for an index insurance product?  2) Does fisher heterogeneity lead to adverse selection, that diminishes viability and conservation gains? 3) Can we tease apart the nature of risk increasing and decreasing inputs in fishery more carefully? For example How could we rapidly identify input risk effects so we can quickly show which fisheries are most suitable for index insurance? I am excited to hear what directions y'all are curious about as well.

I want to give my sincerest thanks to PERC for collecting an incredible collection of academics and researchers to challenge my research, but also encourage my development. I especially want to thank the graduate fellows Nicole, Ben, Brenna, and Micah for [listening to my incoherent mathematical rants and supporting me this summer](https://c.tenor.com/x7gTd1msD20AAAAd/flat-earth.gif). All of them are brilliant researchers and more importantly wonderful people! I hope to keep the connections I have made at PERC and to see everyone again whether at a conference or back here in Bozeman.


